// generated by "sampctl package init"
#include <a_samp>
#include "easyDialog.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

public OnPlayerConnect(playerid)
{
	Dialog_Show(playerid, DialogSetan, DIALOG_STYLE_MSGBOX, "Hallo", "{FFFFFF}Gladys apa kabar!", "Dih", "Baik");
	return 1;
}

DialogResponse DialogResponse(playerid, response, listitem, const string:inputtext[])
{
	if (!response) return Ban(playerid);
	return 1;
}
